//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public History()
        {
            this.PacientInfo = new HashSet<PacientInfo>();
        }
    
        public long Id { get; set; }
        public string Diagnos { get; set; }
        public string Description { get; set; }
        public Nullable<long> DoctorId { get; set; }
    
        public virtual DoctorInfo DoctorInfo { get; set; }
        public virtual ICollection<PacientInfo> PacientInfo { get; set; }
    }
}
