//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalUnit
    {
        public HospitalUnit()
        {
            this.DoctorInfo = new HashSet<DoctorInfo>();
            this.Location = new HashSet<Location>();
        }
    
        public long Id { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<DoctorInfo> DoctorInfo { get; set; }
        public virtual ICollection<Location> Location { get; set; }
    }
}
