//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientInfo
    {
        public PacientInfo()
        {
            this.ReceptionTicket = new HashSet<ReceptionTicket>();
            this.History = new HashSet<History>();
        }
    
        public long Id { get; set; }
        public Nullable<int> CardNumber { get; set; }
        public Nullable<int> SocialNumber { get; set; }
        public int Phone { get; set; }
    
        public virtual ICollection<ReceptionTicket> ReceptionTicket { get; set; }
        public virtual ICollection<History> History { get; set; }
    }
}
