//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionTicket
    {
        public long Id { get; set; }
        public int Numb { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Check { get; set; }
        public Nullable<long> PacientId { get; set; }
        public Nullable<long> DoctorId { get; set; }
    
        public virtual DoctorInfo DoctorInfo { get; set; }
        public virtual PacientInfo PacientInfo { get; set; }
    }
}
